### ISSUE TITLE
Change cache restore-keys to work better across versions

### ISSUE THREAD

**Issue by silvanshade** [llvmup/toolchains#10]
The format is currently:

```yaml
key: ${{ env.TOOLCHAINS_RELEASE_KEY }}-${{ inputs.target-triple-arch }}-${{ inputs.target-triple-sys }}-${{ github.run_id }}
restore-keys: ${{ env.TOOLCHAINS_RELEASE_KEY }}-${{ inputs.target-triple-arch }}-${{ inputs.target-triple-sys }}
```

We should change to the following:

```yaml
key: ${{ inputs.target-triple-arch }}-${{ inputs.target-triple-sys }}-${{ env.TOOLCHAINS_RELEASE_KEY }}-${{ github.run_id }}
restore-keys: |
  ${{ inputs.target-triple-arch }}-${{ inputs.target-triple-sys }}-${{ env.TOOLCHAINS_RELEASE_KEY }}
  ${{ inputs.target-triple-arch }}-${{ inputs.target-triple-sys }}
```

This will allow caches to still partially match across versions. Note that we will have to make this change across 2 steps in order to maintain the current cache (the first step including an additional `restore-key` entry for the current format).
